### ISSUE TITLE
cardMedia - Spotify Tracklist kann "?" im Track enthalten

### ISSUE THREAD

**Issue by Armilar** [ticaki/ioBroker.nspanel-lovelace-ui#20]
![image](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/18b311d6-352d-46b9-896b-f2036cf20914)

![image](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/d98c8638-ba54-4a9d-8f54-615a6bdc08f8)

JSON-Baum
[spotify-premium (2).json](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/files/14403803/spotify-premium.2.json)

Kurz vorab: Es ist die Frage, ob der Name Spotify-Playlist korrekt ist, da diese InSel nur Tracks enthält und es eine weiter Liste (weiterer Feature Request) gibt, die Playlists zur Auswahl enthält? Ich würde um im Code den Unterschied schneller zu finden, den Begriff TrackLists oder TitleTracks verwenden.

Die InSel-Einträge werden durch "?" getrennt an das Panel gesendet. Wenn ein Track ein "?" enthält, dann wird ein leerer Eintrag erzeugt.

Beispiel:

Aktuell:
Brüder?God of War?My Mother Told Me?**Wo sind die Clowns?**?KEiNE REGELN?Odins Raben?Kaufmann und Maid?Pray To The Hunter?The Dragonborn Comes?Heute Nacht?Loki?Heimdall?Taugenichts?Hypa Hypa?Für immer jung?Große Träume?Königsgarde?Alive now?Nachts weinen die Solda?Dorn im Ohr?Mittelfinger Richtung Z?Ein Wort fliegt wie ein?Rattenfänger?Brunhild?Löwenherz?Nichts bleibt mehr?Der haarige Kobold?Brot und Spiele?Seitdem du weg bist?Wellerman?Mauern aus Angst?Besorgter Bürger?Spielmannsschwur?Hypa Hypa?Geboren um frei zu sein?Eulenspiegel?Vermessung des Glücks?Unsere Zeit?Satans Fall?Pack?Prometheus?Bring mich zurück?Wachstum über alles?Veitstanz?We Drink Your Blood?Nie allein?IX?Maria 

Korrekt:
Brüder?God of War?My Mother Told Me?**Wo sind die Clowns**?KEiNE REGELN?Odins Raben?Kaufmann und Maid?Pray To The Hunter?The Dragonborn Comes?Heute Nacht?Loki?Heimdall?Taugenichts?Hypa Hypa?Für immer jung?Große Träume?Königsgarde?Alive now?Nachts weinen die Solda?Dorn im Ohr?Mittelfinger Richtung Z?Ein Wort fliegt wie ein?Rattenfänger?Brunhild?Löwenherz?Nichts bleibt mehr?Der haarige Kobold?Brot und Spiele?Seitdem du weg bist?Wellerman?Mauern aus Angst?Besorgter Bürger?Spielmannsschwur?Hypa Hypa?Geboren um frei zu sein?Eulenspiegel?Vermessung des Glücks?Unsere Zeit?Satans Fall?Pack?Prometheus?Bring mich zurück?Wachstum über alles?Veitstanz?We Drink Your Blood?Nie allein?IX?Maria 

Abgewandeltes Beispiel aus dem NSPanelTs.ts:

Wichtig ist das Einschränken, der Max Einträge und das Bereinigen des Inhaltes
```
let val = getState('spotify-premium.0.player.playlist.trackListArray').val;
                                
let temp_array: string[] = [];
for (let track_index = 0; track_index < 48; track_index++) {
    let temp_cut_array = getAttr(val, track_index + ".title");
    if (temp_cut_array != undefined) {
        temp_cut_array = (temp_cut_array.replace("?", "")).split(" -");
        temp_cut_array = temp_cut_array[0].split(" (");
        temp_cut_array = temp_cut_array[0];
        if (String(temp_cut_array[0]).length >= 22) {
            temp_array[track_index] = temp_cut_array.substring(0, 20) + "..";
        } else {
            temp_array[track_index] = temp_cut_array.substring(0, 23);
        }
    }
    else {
        break;
    }
}

log(temp_array.join("?"));
```

* spotify-premium.0.player.playlist.trackListArray = Playlist, die unter **.title** den Titel beinhaltet 
* mit der Rückgabe des Index aus der InSel muss der Wert um 1 inkremetiert werden

Beispiel
```
setState(spotify-premium.0.playlist.trackNo', parseInt(words[4]) + 1); 
```
* Um den aktuell abgespielten Titel in der Tracklist blau hinterlegt anzuzeigen wird folgender Datenpunkt benutzt:
spotify-premium.0.player.trackName

Damit dieser in der Playlist korrekt hinterlegt wird, muss dieser ebenfalls bereinigt werden (siehe Auszug NSPanelTs.ts):

```
 actualState = getState(pageItem.adapterPlayerInstance + 'player.trackName').val;
 actualState = (actualState.replace('?', '')).split(' -');
 actualState = actualState[0].split(" (");
 actualState = formatInSelText(actualState[0]);
```
aktuell ist diese immer Im 2. Eintrag der InSel

Achtung:
![image](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/3de037e4-372f-4e0e-9d7d-8a036c553bf3)
Titel auch im Template falsch geschrieben --> title wäre korrekt

**Comment by ticaki** [comment]
Ist noch nicht ganz behoben. ? werden jetzt mit ' ' ersetzt, title korrigiert, Titel werden über die id abgespielt. alles was mit namen zu  tun hat wird nur für den nutzer verwendet.

**Comment by Armilar** [comment]
![Nextion_Editor_MfFQAMKGpC](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/85741c78-d16f-4744-a7ca-197ada3dc260)

Nope:
Du kannst zwar einen Song auswählen, damit wechselt allerdings der Mode auf diesen einen Track und die Playlist ist danach obsolet, was zur folge hat, dass die Tracklist ebenfalls leer ist.

Funktioniert offensichtlich nur über die trackNo

Die Bereinigung greift allerdings:
![image](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/8316e16a-17cd-4ad2-b4bb-811774560c0a)

**Comment by ticaki** [comment]
Schade beginnt trackno mit 0 oder 1?

**Comment by Armilar** [comment]
mit der 1

**Comment by ticaki** [comment]
ok index beginnt bei der 1 jetzt und wird wieder trackNo verwendet.

**Comment by Armilar** [comment]
![Nextion_Editor_DdPhwuI21R](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/98f82ce9-f3e2-41e2-a0ab-88340471c08f)

* Auswahl des Tracks funktioniert
* Aktualisierung des aktuell abgespielten oder gewählten Titels funktioniert noch nicht

**Comment by Armilar** [comment]
Ist jetzt okay

![Nextion_Editor_yhuI2VwZe0](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/ece53e21-7672-4982-9a8c-d438bcc59b3a)
