### ISSUE TITLE
Screensaver verliert Uhrzeit und Datum

### ISSUE THREAD

**Issue by Armilar** [ticaki/ioBroker.nspanel-lovelace-ui#30]
![image](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/4776c459-b309-4a1e-9d37-7741fbc009c3)

Beobchte mal, ob ich da ne Logik für die Ursache finde - ggfs. auch eine Geschwindigkeitssache?

**Comment by tt-tom17** [comment]
habe ich auch manchmal

**Comment by ticaki** [comment]
Das von TT-Tom kommt klar vom fehlenden Await . Da Armilar das aber mitten im Betrieb hat, hab ich keine Plan wieso das gelöscht wird.
Gibt jetzt eine "Warn" meldung im Code die immer dann erscheint wenn etwas einen internen State abgesehen vom value verändert.

**Comment by ticaki** [comment]
Denke ich hab den Fehler gerade gefunden, wenn alle trigger entfernt wurden, werden die Einträge dazu gelöscht, da hab ich nun internal ausgenommen.

**Comment by Armilar** [comment]
Sollte kein Thema sein - der Screensaver besteht quasi aus Triggern

Sieht aktuell auch gut aus... Beobachte noch und schließe das Issue wenn bis morgen nichts mehr auftaucht

**Comment by ticaki** [comment]
Wie sieht es jetzt aus?

**Comment by tt-tom17** [comment]
einer Seite geschlossen werden.

**Comment by Armilar** [comment]
Hab jetzt das Live NSPanel 1 Woche mit dem Adapter laufen... Nichts negatives mehr aufgefallen --> wird geschlossen
