### ISSUE TITLE
cardThermo - Serial nicht komplett

### ISSUE THREAD

**Issue by Armilar** [ticaki/ioBroker.nspanel-lovelace-ui#31]
![image](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/6d63cc60-f4eb-4479-8d86-407a8b08e27c)

[Serial-Analyse cardThermo.xlsx](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/files/14410164/Serial-Analyse.cardThermo.xlsx)

Habe die Analyse der Parameter mal durchgeführt

Zwei Dinge sind aufgefallen
* Parameter 17 - Text 4th Box Left Side --> ist leer
* Parameter 58 - Schalter popupThermo --> ist leer --> 0 = an / 1 = aus (wenn keine InSel-Parameter definiert)

**Comment by ticaki** [comment]
Hier fehlt mir ebenfalls was nun der Fehler sein soll bzw. was das erwartete Verhalten ist.  

> Parameter 17 - Text 4th Box Left Side --> ist leer

Wenn da nix drin steht ist das leer. Die Seite hat 5 Textfelder ohne irgendeinen Bezug zueinander.

**Comment by Armilar** [comment]
Erledigt:

![image](https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/assets/102996011/2db99699-1633-4b1d-85a4-e3f22839fd22)
