### ISSUE TITLE
Weblate could not merge upstream changes while updating the repository.

### ISSUE THREAD

**Issue by mcm1957** [ticaki/ioBroker.nspanel-lovelace-ui#48]
Could not merge the repository.
Weblate could not merge upstream changes while updating the repository.
Rebasing (1/2)
error: could not apply b476ecb... Translated using Weblate (German)
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply b476ecb... Translated using Weblate (German)
Auto-merging admin/i18n/de/translations.json
CONFLICT (content): Merge conflict in admin/i18n/de/translations.json
 (1)
Typical workflow for fixing merge conflicts
1.	Commit all pending changes in Weblate and lock the translation component.
wlc commit; wlc lock 
2.	Add Weblate exported repository as a remote.
git remote add weblate https://weblate.iobroker.net/git/adapters/nspanel-lovelace-ui/ ; git remote update weblate 
3.	Merge Weblate changes and resolve any conflicts.
git merge weblate/main 
4.	Push changes into upstream repository.
git push origin main 
5.	Weblate should now be able to see updated repository and you can unlock it.
wlc pull ; wlc unlock

**Comment by ticaki** [comment]
done
