### ISSUE TITLE
write: false zu createStateAsync hinzufügen

### ISSUE THREAD

**Issue by ticaki** [ticaki/ioBroker.nspanel-lovelace-ui#5]
Ihr könntet mir den Gefallen tun und bei allen createState... im common.write hinzufügen. true für States die der Nutzer beschreiben kann, sollen könne und false für alles was er nur lesen soll. 

```
await createStateAsync(NSPanel_Path + 'IoBroker.ScriptName', 'v' + javaScriptVersion, { type: 'string', write: false });
```

**Comment by Armilar** [comment]
Done
